//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the laserscan_to_pointcloud package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __laserscan_to_pointcloud__LASERSCANTOPOINTCLOUDASSEMBLERCONFIG_H__
#define __laserscan_to_pointcloud__LASERSCANTOPOINTCLOUDASSEMBLERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace laserscan_to_pointcloud
{
  class LaserScanToPointcloudAssemblerConfigStatics;

  class LaserScanToPointcloudAssemblerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(LaserScanToPointcloudAssemblerConfig &config, const LaserScanToPointcloudAssemblerConfig &max, const LaserScanToPointcloudAssemblerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const LaserScanToPointcloudAssemblerConfig &config1, const LaserScanToPointcloudAssemblerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, LaserScanToPointcloudAssemblerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const LaserScanToPointcloudAssemblerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LaserScanToPointcloudAssemblerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const LaserScanToPointcloudAssemblerConfig &config) const = 0;
      virtual void getValue(const LaserScanToPointcloudAssemblerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T LaserScanToPointcloudAssemblerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T LaserScanToPointcloudAssemblerConfig::* field;

      virtual void clamp(LaserScanToPointcloudAssemblerConfig &config, const LaserScanToPointcloudAssemblerConfig &max, const LaserScanToPointcloudAssemblerConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const LaserScanToPointcloudAssemblerConfig &config1, const LaserScanToPointcloudAssemblerConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, LaserScanToPointcloudAssemblerConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const LaserScanToPointcloudAssemblerConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LaserScanToPointcloudAssemblerConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const LaserScanToPointcloudAssemblerConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const LaserScanToPointcloudAssemblerConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, LaserScanToPointcloudAssemblerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, LaserScanToPointcloudAssemblerConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<LaserScanToPointcloudAssemblerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(LaserScanToPointcloudAssemblerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("laser_scan_topics"==(*_i)->name){laser_scan_topics = boost::any_cast<std::string>(val);}
        if("pointcloud_publish_topic"==(*_i)->name){pointcloud_publish_topic = boost::any_cast<std::string>(val);}
        if("number_of_scans_to_assemble_per_cloud"==(*_i)->name){number_of_scans_to_assemble_per_cloud = boost::any_cast<int>(val);}
        if("timeout_for_cloud_assembly"==(*_i)->name){timeout_for_cloud_assembly = boost::any_cast<double>(val);}
        if("target_frame"==(*_i)->name){target_frame = boost::any_cast<std::string>(val);}
        if("recovery_frame"==(*_i)->name){recovery_frame = boost::any_cast<std::string>(val);}
        if("min_range_cutoff_percentage_offset"==(*_i)->name){min_range_cutoff_percentage_offset = boost::any_cast<double>(val);}
        if("max_range_cutoff_percentage_offset"==(*_i)->name){max_range_cutoff_percentage_offset = boost::any_cast<double>(val);}
        if("include_laser_intensity"==(*_i)->name){include_laser_intensity = boost::any_cast<bool>(val);}
        if("number_of_tf_queries_for_spherical_interpolation"==(*_i)->name){number_of_tf_queries_for_spherical_interpolation = boost::any_cast<int>(val);}
      }
    }

    std::string laser_scan_topics;
std::string pointcloud_publish_topic;
int number_of_scans_to_assemble_per_cloud;
double timeout_for_cloud_assembly;
std::string target_frame;
std::string recovery_frame;
double min_range_cutoff_percentage_offset;
double max_range_cutoff_percentage_offset;
bool include_laser_intensity;
int number_of_tf_queries_for_spherical_interpolation;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string laser_scan_topics;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string pointcloud_publish_topic;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int number_of_scans_to_assemble_per_cloud;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double timeout_for_cloud_assembly;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string target_frame;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string recovery_frame;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_range_cutoff_percentage_offset;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_range_cutoff_percentage_offset;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool include_laser_intensity;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int number_of_tf_queries_for_spherical_interpolation;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("LaserScanToPointcloudAssemblerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const LaserScanToPointcloudAssemblerConfig &__max__ = __getMax__();
      const LaserScanToPointcloudAssemblerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const LaserScanToPointcloudAssemblerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const LaserScanToPointcloudAssemblerConfig &__getDefault__();
    static const LaserScanToPointcloudAssemblerConfig &__getMax__();
    static const LaserScanToPointcloudAssemblerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const LaserScanToPointcloudAssemblerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void LaserScanToPointcloudAssemblerConfig::ParamDescription<std::string>::clamp(LaserScanToPointcloudAssemblerConfig &config, const LaserScanToPointcloudAssemblerConfig &max, const LaserScanToPointcloudAssemblerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class LaserScanToPointcloudAssemblerConfigStatics
  {
    friend class LaserScanToPointcloudAssemblerConfig;

    LaserScanToPointcloudAssemblerConfigStatics()
    {
LaserScanToPointcloudAssemblerConfig::GroupDescription<LaserScanToPointcloudAssemblerConfig::DEFAULT, LaserScanToPointcloudAssemblerConfig> Default("Default", "", 0, 0, true, &LaserScanToPointcloudAssemblerConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.laser_scan_topics = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.laser_scan_topics = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.laser_scan_topics = "/tilt_scan+/base_scan";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<std::string>("laser_scan_topics", "str", 1, "Topics with LaserScans to assemble separated by +", "", &LaserScanToPointcloudAssemblerConfig::laser_scan_topics)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<std::string>("laser_scan_topics", "str", 1, "Topics with LaserScans to assemble separated by +", "", &LaserScanToPointcloudAssemblerConfig::laser_scan_topics)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pointcloud_publish_topic = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pointcloud_publish_topic = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pointcloud_publish_topic = "assembled_pointcloud";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<std::string>("pointcloud_publish_topic", "str", 1, "Topic where the assembled scans will be published", "", &LaserScanToPointcloudAssemblerConfig::pointcloud_publish_topic)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<std::string>("pointcloud_publish_topic", "str", 1, "Topic where the assembled scans will be published", "", &LaserScanToPointcloudAssemblerConfig::pointcloud_publish_topic)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.number_of_scans_to_assemble_per_cloud = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.number_of_scans_to_assemble_per_cloud = 2147483647;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.number_of_scans_to_assemble_per_cloud = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<int>("number_of_scans_to_assemble_per_cloud", "int", 1, "Number of LaserScans to assemble for each PointCloud2 published", "", &LaserScanToPointcloudAssemblerConfig::number_of_scans_to_assemble_per_cloud)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<int>("number_of_scans_to_assemble_per_cloud", "int", 1, "Number of LaserScans to assemble for each PointCloud2 published", "", &LaserScanToPointcloudAssemblerConfig::number_of_scans_to_assemble_per_cloud)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.timeout_for_cloud_assembly = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.timeout_for_cloud_assembly = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.timeout_for_cloud_assembly = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<double>("timeout_for_cloud_assembly", "double", 1, "Maximum number of seconds for each cloud assembly", "", &LaserScanToPointcloudAssemblerConfig::timeout_for_cloud_assembly)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<double>("timeout_for_cloud_assembly", "double", 1, "Maximum number of seconds for each cloud assembly", "", &LaserScanToPointcloudAssemblerConfig::timeout_for_cloud_assembly)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_frame = "map";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<std::string>("target_frame", "str", 1, "Frame of reference in which the scans are going to be transformed", "", &LaserScanToPointcloudAssemblerConfig::target_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<std::string>("target_frame", "str", 1, "Frame of reference in which the scans are going to be transformed", "", &LaserScanToPointcloudAssemblerConfig::target_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.recovery_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.recovery_frame = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.recovery_frame = "odom";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<std::string>("recovery_frame", "str", 1, "Frame used to retrieve the current tf between [sensor -> recovery_frame] in order to use the last known tf between [recovery_frame -> target_frame]. If empty disables recovery", "", &LaserScanToPointcloudAssemblerConfig::recovery_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<std::string>("recovery_frame", "str", 1, "Frame used to retrieve the current tf between [sensor -> recovery_frame] in order to use the last known tf between [recovery_frame -> target_frame]. If empty disables recovery", "", &LaserScanToPointcloudAssemblerConfig::recovery_frame)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_range_cutoff_percentage_offset = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_range_cutoff_percentage_offset = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_range_cutoff_percentage_offset = 1.05;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<double>("min_range_cutoff_percentage_offset", "double", 1, "Value that is going to be multiplied with the min_range reported with in the laser scan to remove points too far or too close", "", &LaserScanToPointcloudAssemblerConfig::min_range_cutoff_percentage_offset)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<double>("min_range_cutoff_percentage_offset", "double", 1, "Value that is going to be multiplied with the min_range reported with in the laser scan to remove points too far or too close", "", &LaserScanToPointcloudAssemblerConfig::min_range_cutoff_percentage_offset)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_range_cutoff_percentage_offset = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_range_cutoff_percentage_offset = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_range_cutoff_percentage_offset = 0.95;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<double>("max_range_cutoff_percentage_offset", "double", 1, "Value that is going to be multiplied with the max_range reported with in the laser scan to remove points too far or too close", "", &LaserScanToPointcloudAssemblerConfig::max_range_cutoff_percentage_offset)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<double>("max_range_cutoff_percentage_offset", "double", 1, "Value that is going to be multiplied with the max_range reported with in the laser scan to remove points too far or too close", "", &LaserScanToPointcloudAssemblerConfig::max_range_cutoff_percentage_offset)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.include_laser_intensity = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.include_laser_intensity = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.include_laser_intensity = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<bool>("include_laser_intensity", "bool", 1, "Flag to include laser intensities in Pointcloud2", "", &LaserScanToPointcloudAssemblerConfig::include_laser_intensity)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<bool>("include_laser_intensity", "bool", 1, "Flag to include laser intensities in Pointcloud2", "", &LaserScanToPointcloudAssemblerConfig::include_laser_intensity)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.number_of_tf_queries_for_spherical_interpolation = -2147483648;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.number_of_tf_queries_for_spherical_interpolation = 2147483647;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.number_of_tf_queries_for_spherical_interpolation = 4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<int>("number_of_tf_queries_for_spherical_interpolation", "int", 1, "Number of tfs used to performed laser spherical interpolation (if < 2 no interpolation is done and the tf in the middle of the scan time is used)", "", &LaserScanToPointcloudAssemblerConfig::number_of_tf_queries_for_spherical_interpolation)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::ParamDescription<int>("number_of_tf_queries_for_spherical_interpolation", "int", 1, "Number of tfs used to performed laser spherical interpolation (if < 2 no interpolation is done and the tf in the middle of the scan time is used)", "", &LaserScanToPointcloudAssemblerConfig::number_of_tf_queries_for_spherical_interpolation)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LaserScanToPointcloudAssemblerConfig::AbstractGroupDescriptionConstPtr(new LaserScanToPointcloudAssemblerConfig::GroupDescription<LaserScanToPointcloudAssemblerConfig::DEFAULT, LaserScanToPointcloudAssemblerConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<LaserScanToPointcloudAssemblerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<LaserScanToPointcloudAssemblerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    LaserScanToPointcloudAssemblerConfig __max__;
    LaserScanToPointcloudAssemblerConfig __min__;
    LaserScanToPointcloudAssemblerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const LaserScanToPointcloudAssemblerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static LaserScanToPointcloudAssemblerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &LaserScanToPointcloudAssemblerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const LaserScanToPointcloudAssemblerConfig &LaserScanToPointcloudAssemblerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const LaserScanToPointcloudAssemblerConfig &LaserScanToPointcloudAssemblerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const LaserScanToPointcloudAssemblerConfig &LaserScanToPointcloudAssemblerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<LaserScanToPointcloudAssemblerConfig::AbstractParamDescriptionConstPtr> &LaserScanToPointcloudAssemblerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<LaserScanToPointcloudAssemblerConfig::AbstractGroupDescriptionConstPtr> &LaserScanToPointcloudAssemblerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const LaserScanToPointcloudAssemblerConfigStatics *LaserScanToPointcloudAssemblerConfig::__get_statics__()
  {
    const static LaserScanToPointcloudAssemblerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = LaserScanToPointcloudAssemblerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __LASERSCANTOPOINTCLOUDASSEMBLERRECONFIGURATOR_H__
